branches:
  only:
  - master
  - "/^release-v[\\d.-]+$/"
language: java
jdk:
- oraclejdk8
before_install:
- ls
- git config --global user.name "Travis CI"
- git config --global user.email "user@example.com"
- export TRAVIS_COMMIT_MSG="$(git log --format=%B -n 1 | head -n 1)"
before_cache:
- rm -rf $HOME/.m2/repository/
cache:
  directories:
  - "$HOME/.m2/repository"
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- "./deploy.sh"
env:
  global:
    secure: f2zSvAhqwK+3ISCSRkOgwlm3Dyxbs6DDJwf4BumVV0L/NrsxxWV7tto0QWD3wPdzGkXjVnz1D9OTshYn87KKDNWT+L3EPeO7WB/aTIBZpGTDqSNNJkZT/T2hVNLkGejr94zIgRVG/9/LpNtN1gv2dwaI1ywe6IKDoHEMf8VkhNdsWBLZBmOzo3L+xI30RETDnWGpQAjiXvSg3iRffxkNI3/HwzLdECXKeU2ORXuDTIrs6iX+38TlQVWHokJ+wteT1kSuVdcht4PvCLYGCtWgABcsnl8UnwBXVFsLz6GfNOz1X87zj2QNhRQW0hRyZpuvDHE/Dg1ZWGs0LUQNB2+4eK2Q0ZUm/VR5DQJQGdN8BAQwvkjKgG4dqLrrD+HxGy4AIbVuKd7WO4lYdn8sLGPEsI7ebU5h/j8NMt3f5ILcKNXokXsZj5DQHTpfeWkzI+c1ysf+T2T7uaYR0UDMQLc02o6NObikiXHbMkdyO/mtoa6/no02j6fM0V3AnfuH0WzmzybTXUL5VfCsrs2M/vM6USVbK+FHgLezfIKphVUGTTsfkWRNO+1pOqJLKOZb/IY2cfVIM7zR+Yf7d8KTLw88DAX09SbkZ/zLjE742kr+RRxcUFphvct/ZoknaJ8hPD0PsBoHqIIb/AfieMDO+NRxV7f9VTHXmO/NSCtvCmhPHNI=
