branches:
  only:
  - master
  - /^release-v[\d.-]+$/
language: java
jdk:
 - oraclejdk8
before_install:
 - ls -la
before_cache:
 - rm -rf $HOME/.m2/repository/
cache:
  directories:
  - $HOME/.m2/repository
script:
 - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B -n 1)\""
 - "./deploy.sh"
