branches:
  only:
  - master
  - /^release-v[\d.-]+$/
language: java
jdk:
 - oraclejdk8
before_install:
  - ls
  - cat .travis/deploy_key.pem
  - git config --global user.name "Travis CI"
  - git config --global user.email "user@example.com"
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
before_cache:
 - rm -rf $HOME/.m2/repository/
cache:
  directories:
  - $HOME/.m2/repository
script:
 - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B -n 1 | head -n 1)\""
 - "./deploy.sh"
